include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    -
    - always_declare_return_types
    - always_specify_types
    - avoid_dynamic_calls

    - avoid_function_literals_in_foreach_calls
    - avoid_classes_with_only_static_members
    - prefer_constructors_over_static_methods
    - type_annotate_public_apis
    - type_init_formals

    - always_put_control_body_on_new_line
    - curly_braces_in_flow_control_structures
    #- require_trailing_commas
    - avoid_redundant_argument_values

    - avoid_returning_null
    - avoid_returning_null_for_future
    - avoid_returning_null_for_void
    - cast_nullable_to_non_nullable
    - unnecessary_null_in_if_null_operators

    - avoid_positional_boolean_parameters
    - prefer_function_declarations_over_variables
    - prefer_final_locals
    - unnecessary_this

    #- package_api_docs
    #- public_member_api_docs
    #- comment_references
